name: recepi_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  get_cli: ^1.8.4
  flutter_animate: ^4.5.0
  google_fonts: ^4.0.4
  freezed: ^2.4.2
  timelines: ^0.1.0
  freezed_annotation: ^2.4.1
  shimmer: ^3.0.0
  json_annotation: ^4.8.1
  image_picker: ^1.0.4
  sliding_up_panel: ^2.0.0+1
  flex_color_scheme: ^7.2.0
  shared_preferences: ^2.2.1
  firebase_core: ^2.27.0 
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  cached_network_image: ^3.3.1
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^5.8.0
  gap: ^3.0.1
  http: ^0.13.6
  lottie: ^3.0.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8
  sign_in_button: ^3.2.0
  get_storage: ^2.1.1
  rename: ^3.0.2


dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
