// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuQAi3-okEOr0yGSD2-Y3GxLCW2OMkyAc',
    appId: '1:80740378044:web:f495ce94966e8f239bb7b9',
    messagingSenderId: '80740378044',
    projectId: 'recipeapp-b79b1',
    authDomain: 'recipeapp-b79b1.firebaseapp.com',
    storageBucket: 'recipeapp-b79b1.appspot.com',
    measurementId: 'G-P7FE1M09E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv2H_peFAJmj1LzyKFpv8ZL1-h43ctbzI',
    appId: '1:80740378044:android:0a9b54527e2c77349bb7b9',
    messagingSenderId: '80740378044',
    projectId: 'recipeapp-b79b1',
    storageBucket: 'recipeapp-b79b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLYOMuofjX9afbovRm4FUb8UkpYJEQ6s',
    appId: '1:80740378044:ios:07a9d108a344a1129bb7b9',
    messagingSenderId: '80740378044',
    projectId: 'recipeapp-b79b1',
    storageBucket: 'recipeapp-b79b1.appspot.com',
    iosBundleId: 'com.sumanmaitryee.recepiApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMLYOMuofjX9afbovRm4FUb8UkpYJEQ6s',
    appId: '1:80740378044:ios:e26aae7b4320682f9bb7b9',
    messagingSenderId: '80740378044',
    projectId: 'recipeapp-b79b1',
    storageBucket: 'recipeapp-b79b1.appspot.com',
    iosBundleId: 'com.sumanmaitryee.recepiApplication.RunnerTests',
  );
}
